### ISSUE TITLE
Notify the user on cookie usage

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck-site#40]
With the new regulations on cookies, we need to at least notify the user that by visiting the site he must agree to cookie usage.

And simply by including the google custom site search feature, we already get cookies from the external scripts, which we do not even control.

Without that (we can always remove the custom search engine feature and just redirect the user to google or use some integrated javascript search engine provided by some jekyll plugin) we would not have any cookies at all.

Using an embedded search facility, however, will have a negative impact on mobile devices and their overall data volumes...

Alternatively, I could host a search engine on my own coldrye.eu server, which lies dormant so far... 

@pana-cc do you know a better solution?

**Comment by silkentrance** [comment]
For a search engine alternative I looked at open search server, which looks ok but costs 19$ per month, which is not something I would be willing to pay for a site that has so little content :)

And hosting that beast on a private server also looks like as it was some heavy undertaking.

**Comment by pana-cc** [comment]
I don’t know.

**Comment by pana-cc** [comment]
I don’t think we have so much content. Just nuke the search for now.

**Comment by silkentrance** [comment]
@pana-cc I will outcomment the search from the existing sources in the jekyll theme.

**Comment by silkentrance** [comment]
Done. You have zero cookies:

![image](https://user-images.githubusercontent.com/6068824/55981461-05490780-5c97-11e9-980a-2fa834382f10.png)
